import { defaultOutputSettings } from "./presets";
import { makeImageLayer, makeShapeLayer, makeTextLayer } from "./layerFactory";
import { createInitialLayers } from "./sampleData";
import type { OutputSettings, ThumbnailLayer } from "./types";

export interface DefaultTemplateDefinition {
  id: string;
  name: string;
  description: string;
  settings: OutputSettings;
  createLayers: () => ThumbnailLayer[];
}

export const defaultTemplates: DefaultTemplateDefinition[] = [
  {
    id: "creator-live",
    name: "Creator Live",
    description: "Bold livestream thumbnail with title plate and platform tag.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: createInitialLayers,
  },
  {
    id: "product-review",
    name: "Product Review",
    description: "Review layout with large product area, score badge, and verdict text.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Soft background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0, blur: 4, brightness: 78, contrast: 120, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Product frame",
        shape: "rect",
        x: 716,
        y: 92,
        width: 430,
        height: 430,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        rotation: 3,
      }),
      makeShapeLayer({
        name: "Score badge",
        shape: "ellipse",
        x: 884,
        y: 486,
        width: 220,
        height: 132,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
        rotation: -8,
      }),
      makeTextLayer({
        name: "Review title",
        x: 70,
        y: 86,
        width: 600,
        height: 220,
        text: "WORTH\nBUYING?",
        fontSize: 96,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Verdict",
        x: 96,
        y: 526,
        width: 560,
        height: 74,
        text: "FULL REVIEW",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 5,
      }),
      makeTextLayer({
        name: "Score text",
        x: 902,
        y: 518,
        width: 180,
        height: 72,
        text: "9/10",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  {
    id: "tutorial-steps",
    name: "Tutorial Steps",
    description: "Structured how-to thumbnail with numbered chips and a clear action title.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Desk background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.16, blur: 2, brightness: 86, contrast: 118, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Header band",
        x: 0,
        y: 0,
        width: 1280,
        height: 150,
        fill: "#152033",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "How-to title",
        x: 76,
        y: 46,
        width: 820,
        height: 92,
        text: "MAKE IT IN 5 MINUTES",
        fontSize: 58,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 5,
      }),
      ...[0, 1, 2].map((index) =>
        makeShapeLayer({
          name: `Step ${index + 1} chip`,
          shape: "rect",
          x: 90 + index * 382,
          y: 468,
          width: 292,
          height: 118,
          fill: index === 1 ? "#ff4f5f" : "#ffffff",
          strokeColor: "#111827",
          strokeWidth: 7,
          rotation: index === 1 ? -2 : 2,
        }),
      ),
      ...["Plan", "Build", "Export"].map((text, index) =>
        makeTextLayer({
          name: `Step ${index + 1} label`,
          x: 112 + index * 382,
          y: 494,
          width: 248,
          height: 68,
          text: `${index + 1}. ${text}`,
          fontSize: 42,
          fontFamily: "Arial Black, Arial, sans-serif",
          fontWeight: "900",
          color: index === 1 ? "#ffffff" : "#111827",
          strokeColor: index === 1 ? "#111827" : "#ffffff",
          strokeWidth: 3,
          align: "center",
        }),
      ),
    ],
  },
  {
    id: "shorts-quote",
    name: "Shorts Quote",
    description: "Vertical quote-first layout for Shorts, Reels, and portrait clips.",
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Portrait background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0, blur: 6, brightness: 70, contrast: 128, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Quote panel",
        x: 86,
        y: 520,
        width: 908,
        height: 610,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        opacity: 0.94,
      }),
      makeTextLayer({
        name: "Quote text",
        x: 134,
        y: 612,
        width: 812,
        height: 386,
        text: "ONE IDEA\nCHANGED\nEVERYTHING",
        fontSize: 112,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffd166",
        strokeWidth: 6,
        align: "center",
        lineHeight: 0.94,
      }),
      makeShapeLayer({
        name: "Accent slash",
        x: 92,
        y: 1238,
        width: 896,
        height: 42,
        fill: "#ff4f5f",
        strokeWidth: 0,
        rotation: -3,
      }),
      makeTextLayer({
        name: "Series tag",
        x: 130,
        y: 1304,
        width: 820,
        height: 88,
        text: "SHORT CLIP",
        fontSize: 58,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 7,
        align: "center",
      }),
    ],
  },
  {
    id: "breaking-news",
    name: "Breaking News",
    description: "Urgent news thumbnail with a high-contrast ticker and headline lockup.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "News background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.35, blur: 3, brightness: 62, contrast: 132, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Red headline block",
        x: 0,
        y: 468,
        width: 1280,
        height: 174,
        fill: "#d90429",
        strokeWidth: 0,
        opacity: 0.96,
      }),
      makeShapeLayer({
        name: "Top alert bar",
        x: 0,
        y: 54,
        width: 1280,
        height: 76,
        fill: "#ffd166",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Diagonal flash",
        x: 884,
        y: 116,
        width: 98,
        height: 420,
        rotation: 18,
        fill: "#ffffff",
        strokeWidth: 0,
        opacity: 0.86,
      }),
      makeTextLayer({
        name: "Alert label",
        x: 58,
        y: 66,
        width: 468,
        height: 56,
        text: "BREAKING",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "News title",
        x: 58,
        y: 490,
        width: 1030,
        height: 120,
        text: "WHAT JUST HAPPENED?",
        fontSize: 82,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 8,
      }),
      makeTextLayer({
        name: "Time tag",
        x: 920,
        y: 74,
        width: 292,
        height: 44,
        text: "LIVE UPDATE",
        fontSize: 34,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 3,
        align: "right",
      }),
    ],
  },
  {
    id: "versus-comparison",
    name: "Versus Comparison",
    description: "Two-column comparison layout with a central VS badge and clear choices.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Left field",
        x: 0,
        y: 0,
        width: 640,
        height: 720,
        fill: "#10b6d7",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Right field",
        x: 640,
        y: 0,
        width: 640,
        height: 720,
        fill: "#ff4f5f",
        strokeWidth: 0,
      }),
      makeImageLayer({
        name: "Comparison texture",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        opacity: 0.24,
        effects: { grayscale: 1, blur: 1, brightness: 110, contrast: 126, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Center divider",
        x: 618,
        y: -18,
        width: 44,
        height: 756,
        rotation: -4,
        fill: "#111827",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "VS badge",
        shape: "ellipse",
        x: 518,
        y: 252,
        width: 244,
        height: 196,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 12,
      }),
      makeTextLayer({
        name: "Left option",
        x: 72,
        y: 140,
        width: 472,
        height: 146,
        text: "OPTION A",
        fontSize: 74,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 8,
        align: "center",
      }),
      makeTextLayer({
        name: "Right option",
        x: 732,
        y: 140,
        width: 472,
        height: 146,
        text: "OPTION B",
        fontSize: 74,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 8,
        align: "center",
      }),
      makeTextLayer({
        name: "VS text",
        x: 556,
        y: 300,
        width: 168,
        height: 96,
        text: "VS",
        fontSize: 88,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffd166",
        strokeWidth: 4,
        align: "center",
      }),
      makeTextLayer({
        name: "Comparison caption",
        x: 206,
        y: 576,
        width: 868,
        height: 70,
        text: "WHICH ONE WINS?",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 6,
        align: "center",
      }),
    ],
  },
  {
    id: "gaming-highlight",
    name: "Gaming Highlight",
    description: "Action thumbnail with neon frame, play marker, and score callout.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Gameplay background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0, blur: 2, brightness: 74, contrast: 148, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Neon frame",
        x: 52,
        y: 48,
        width: 1176,
        height: 624,
        fill: "#111827",
        fillOpacity: 0.1,
        strokeColor: "#10b6d7",
        strokeWidth: 12,
        cornerRadius: 22,
      }),
      makeShapeLayer({
        name: "Play triangle",
        shape: "triangle",
        x: 902,
        y: 230,
        width: 210,
        height: 188,
        rotation: 90,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
      }),
      makeShapeLayer({
        name: "Wave underline",
        shape: "line",
        x: 96,
        y: 548,
        width: 560,
        height: 30,
        fill: "#ffffff",
        strokeColor: "#ff4f5f",
        strokeWidth: 14,
        lineStyle: "wave",
      }),
      makeTextLayer({
        name: "Highlight title",
        x: 76,
        y: 116,
        width: 746,
        height: 220,
        text: "INSANE\nCLUTCH",
        fontSize: 100,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Score callout",
        x: 806,
        y: 520,
        width: 336,
        height: 88,
        text: "1 HP WIN",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 7,
        align: "center",
      }),
    ],
  },
  {
    id: "podcast-guest",
    name: "Podcast Guest",
    description: "Square interview card with guest placeholder, topic title, and episode tag.",
    settings: { ...defaultOutputSettings, presetId: "square", width: 1080, height: 1080 },
    createLayers: () => [
      makeShapeLayer({
        name: "Warm backdrop",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#edf2f6",
        strokeWidth: 0,
      }),
      makeImageLayer({
        name: "Soft texture",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        opacity: 0.22,
        effects: { grayscale: 1, blur: 5, brightness: 118, contrast: 82, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Guest portrait frame",
        shape: "ellipse",
        x: 330,
        y: 106,
        width: 420,
        height: 420,
        fill: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 14,
      }),
      makeShapeLayer({
        name: "Episode badge",
        x: 108,
        y: 762,
        width: 864,
        height: 104,
        fill: "#152033",
        strokeWidth: 0,
        cornerRadius: 18,
      }),
      makeTextLayer({
        name: "Podcast title",
        x: 112,
        y: 568,
        width: 856,
        height: 148,
        text: "THE CREATOR\nINTERVIEW",
        fontSize: 70,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        align: "center",
        lineHeight: 0.96,
      }),
      makeTextLayer({
        name: "Episode label",
        x: 144,
        y: 786,
        width: 792,
        height: 58,
        text: "EP. 24  /  NEW GUEST",
        fontSize: 42,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 3,
        align: "center",
      }),
    ],
  },
  {
    id: "event-countdown",
    name: "Event Countdown",
    description: "Countdown announcement layout with date badge and strong event title.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Event background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.08, blur: 2, brightness: 82, contrast: 124, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Countdown card",
        x: 78,
        y: 108,
        width: 430,
        height: 430,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        rotation: -2,
      }),
      makeShapeLayer({
        name: "Date ribbon",
        x: 56,
        y: 552,
        width: 1168,
        height: 96,
        fill: "#10b6d7",
        strokeColor: "#111827",
        strokeWidth: 6,
      }),
      makeTextLayer({
        name: "Countdown number",
        x: 116,
        y: 160,
        width: 352,
        height: 196,
        text: "3",
        fontSize: 198,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ff4f5f",
        strokeColor: "#111827",
        strokeWidth: 8,
        align: "center",
      }),
      makeTextLayer({
        name: "Days label",
        x: 128,
        y: 374,
        width: 326,
        height: 78,
        text: "DAYS",
        fontSize: 56,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeWidth: 0,
        align: "center",
      }),
      makeTextLayer({
        name: "Event title",
        x: 560,
        y: 132,
        width: 600,
        height: 214,
        text: "BIG EVENT\nIS COMING",
        fontSize: 82,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 9,
        lineHeight: 0.92,
      }),
      makeTextLayer({
        name: "Date text",
        x: 104,
        y: 574,
        width: 1072,
        height: 58,
        text: "SAVE THE DATE  /  20:00 START",
        fontSize: 44,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  {
    id: "minimal-launch",
    name: "Minimal Launch",
    description: "Clean product or feature launch layout with calm whitespace and accent lines.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Clean background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        fill: "#f7fafc",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Product block",
        x: 730,
        y: 98,
        width: 396,
        height: 418,
        fill: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 8,
        cornerRadius: 26,
      }),
      makeShapeLayer({
        name: "Accent line one",
        shape: "line",
        x: 88,
        y: 478,
        width: 452,
        height: 18,
        strokeColor: "#10b6d7",
        strokeWidth: 12,
        lineStyle: "solid",
      }),
      makeShapeLayer({
        name: "Accent line two",
        shape: "line",
        x: 88,
        y: 520,
        width: 328,
        height: 18,
        strokeColor: "#ff4f5f",
        strokeWidth: 12,
        lineStyle: "dashed",
      }),
      makeTextLayer({
        name: "Launch eyebrow",
        x: 92,
        y: 120,
        width: 420,
        height: 54,
        text: "NEW RELEASE",
        fontSize: 38,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#10b6d7",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "Launch title",
        x: 86,
        y: 196,
        width: 568,
        height: 196,
        text: "SIMPLE\nBUT POWERFUL",
        fontSize: 78,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        lineHeight: 0.94,
      }),
      makeShapeLayer({
        name: "Tag backing",
        x: 732,
        y: 532,
        width: 392,
        height: 78,
        fill: "#152033",
        strokeWidth: 0,
        cornerRadius: 16,
      }),
      makeTextLayer({
        name: "Launch tag",
        x: 746,
        y: 542,
        width: 364,
        height: 58,
        text: "AVAILABLE NOW",
        fontSize: 36,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
];
