import { defaultOutputSettings } from "./presets";
import { makeImageLayer, makeShapeLayer, makeTextLayer } from "./layerFactory";
import { motionTemplates } from "./motionTemplates";
import { scheduleTemplates } from "./scheduleTemplates";
import { createInitialLayers } from "./sampleData";
import type { OutputSettings, ThumbnailLayer } from "./types";

export type DefaultTemplateCategory = "youtube" | "shorts" | "stream" | "cutout" | "schedule" | "motion";

export interface DefaultTemplateDefinition {
  id: string;
  name: string;
  description: string;
  category: DefaultTemplateCategory;
  previewColors: [string, string, string];
  settings: OutputSettings;
  createLayers: () => ThumbnailLayer[];
}

export const defaultTemplates: DefaultTemplateDefinition[] = [
  {
    id: "creator-live",
    name: "Creator Live",
    description: "Bold livestream thumbnail with title plate and platform tag.",
    category: "stream",
    previewColors: ["#152033", "#10b6d7", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: createInitialLayers,
  },
  {
    id: "product-review",
    name: "Product Review",
    description: "Review layout with large product area, score badge, and verdict text.",
    category: "youtube",
    previewColors: ["#ffffff", "#ffd166", "#111827"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Soft background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0, blur: 4, brightness: 78, contrast: 120, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Product frame",
        shape: "rect",
        x: 716,
        y: 92,
        width: 430,
        height: 430,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        rotation: 3,
      }),
      makeShapeLayer({
        name: "Score badge",
        shape: "ellipse",
        x: 884,
        y: 486,
        width: 220,
        height: 132,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
        rotation: -8,
      }),
      makeTextLayer({
        name: "Review title",
        x: 70,
        y: 86,
        width: 600,
        height: 220,
        text: "WORTH\nBUYING?",
        fontSize: 96,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Verdict",
        x: 96,
        y: 526,
        width: 560,
        height: 74,
        text: "FULL REVIEW",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 5,
      }),
      makeTextLayer({
        name: "Score text",
        x: 902,
        y: 518,
        width: 180,
        height: 72,
        text: "9/10",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  {
    id: "tutorial-steps",
    name: "Tutorial Steps",
    description: "Structured how-to thumbnail with numbered chips and a clear action title.",
    category: "youtube",
    previewColors: ["#152033", "#ffffff", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Desk background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.16, blur: 2, brightness: 86, contrast: 118, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Header band",
        x: 0,
        y: 0,
        width: 1280,
        height: 150,
        fill: "#152033",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "How-to title",
        x: 76,
        y: 46,
        width: 820,
        height: 92,
        text: "MAKE IT IN 5 MINUTES",
        fontSize: 58,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 5,
      }),
      ...[0, 1, 2].map((index) =>
        makeShapeLayer({
          name: `Step ${index + 1} chip`,
          shape: "rect",
          x: 90 + index * 382,
          y: 468,
          width: 292,
          height: 118,
          fill: index === 1 ? "#ff4f5f" : "#ffffff",
          strokeColor: "#111827",
          strokeWidth: 7,
          rotation: index === 1 ? -2 : 2,
        }),
      ),
      ...["Plan", "Build", "Export"].map((text, index) =>
        makeTextLayer({
          name: `Step ${index + 1} label`,
          x: 112 + index * 382,
          y: 494,
          width: 248,
          height: 68,
          text: `${index + 1}. ${text}`,
          fontSize: 42,
          fontFamily: "Arial Black, Arial, sans-serif",
          fontWeight: "900",
          color: index === 1 ? "#ffffff" : "#111827",
          strokeColor: index === 1 ? "#111827" : "#ffffff",
          strokeWidth: 3,
          align: "center",
        }),
      ),
    ],
  },
  {
    id: "shorts-quote",
    name: "Shorts Quote",
    description: "Vertical quote-first layout for Shorts, Reels, and portrait clips.",
    category: "shorts",
    previewColors: ["#111827", "#ffffff", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Portrait background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0, blur: 6, brightness: 70, contrast: 128, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Quote panel",
        x: 86,
        y: 520,
        width: 908,
        height: 610,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        opacity: 0.94,
      }),
      makeTextLayer({
        name: "Quote text",
        x: 134,
        y: 612,
        width: 812,
        height: 386,
        text: "ONE IDEA\nCHANGED\nEVERYTHING",
        fontSize: 112,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffd166",
        strokeWidth: 6,
        align: "center",
        lineHeight: 0.94,
      }),
      makeShapeLayer({
        name: "Accent slash",
        x: 92,
        y: 1238,
        width: 896,
        height: 42,
        fill: "#ff4f5f",
        strokeWidth: 0,
        rotation: -3,
      }),
      makeTextLayer({
        name: "Series tag",
        x: 130,
        y: 1304,
        width: 820,
        height: 88,
        text: "SHORT CLIP",
        fontSize: 58,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 7,
        align: "center",
      }),
    ],
  },
  {
    id: "breaking-news",
    name: "Breaking News",
    description: "Urgent news thumbnail with a high-contrast ticker and headline lockup.",
    category: "stream",
    previewColors: ["#d92d20", "#111827", "#ffffff"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "News background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.35, blur: 3, brightness: 62, contrast: 132, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Red headline block",
        x: 0,
        y: 468,
        width: 1280,
        height: 174,
        fill: "#d90429",
        strokeWidth: 0,
        opacity: 0.96,
      }),
      makeShapeLayer({
        name: "Top alert bar",
        x: 0,
        y: 54,
        width: 1280,
        height: 76,
        fill: "#ffd166",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Diagonal flash",
        x: 884,
        y: 116,
        width: 98,
        height: 420,
        rotation: 18,
        fill: "#ffffff",
        strokeWidth: 0,
        opacity: 0.86,
      }),
      makeTextLayer({
        name: "Alert label",
        x: 58,
        y: 66,
        width: 468,
        height: 56,
        text: "BREAKING",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "News title",
        x: 58,
        y: 490,
        width: 1030,
        height: 120,
        text: "WHAT JUST HAPPENED?",
        fontSize: 82,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 8,
      }),
      makeTextLayer({
        name: "Time tag",
        x: 920,
        y: 74,
        width: 292,
        height: 44,
        text: "LIVE UPDATE",
        fontSize: 34,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 3,
        align: "right",
      }),
    ],
  },
  {
    id: "versus-comparison",
    name: "Versus Comparison",
    description: "Two-column comparison layout with a central VS badge and clear choices.",
    category: "youtube",
    previewColors: ["#10b6d7", "#ffd166", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Left field",
        x: 0,
        y: 0,
        width: 640,
        height: 720,
        fill: "#10b6d7",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Right field",
        x: 640,
        y: 0,
        width: 640,
        height: 720,
        fill: "#ff4f5f",
        strokeWidth: 0,
      }),
      makeImageLayer({
        name: "Comparison texture",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        opacity: 0.24,
        effects: { grayscale: 1, blur: 1, brightness: 110, contrast: 126, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Center divider",
        x: 618,
        y: -18,
        width: 44,
        height: 756,
        rotation: -4,
        fill: "#111827",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "VS badge",
        shape: "ellipse",
        x: 518,
        y: 252,
        width: 244,
        height: 196,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 12,
      }),
      makeTextLayer({
        name: "Left option",
        x: 72,
        y: 140,
        width: 472,
        height: 146,
        text: "OPTION A",
        fontSize: 74,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 8,
        align: "center",
      }),
      makeTextLayer({
        name: "Right option",
        x: 732,
        y: 140,
        width: 472,
        height: 146,
        text: "OPTION B",
        fontSize: 74,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 8,
        align: "center",
      }),
      makeTextLayer({
        name: "VS text",
        x: 556,
        y: 300,
        width: 168,
        height: 96,
        text: "VS",
        fontSize: 88,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffd166",
        strokeWidth: 4,
        align: "center",
      }),
      makeTextLayer({
        name: "Comparison caption",
        x: 206,
        y: 576,
        width: 868,
        height: 70,
        text: "WHICH ONE WINS?",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 6,
        align: "center",
      }),
    ],
  },
  {
    id: "gaming-highlight",
    name: "Gaming Highlight",
    description: "Action thumbnail with neon frame, play marker, and score callout.",
    category: "stream",
    previewColors: ["#111827", "#7c3aed", "#10b6d7"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Gameplay background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0, blur: 2, brightness: 74, contrast: 148, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Neon frame",
        x: 52,
        y: 48,
        width: 1176,
        height: 624,
        fill: "#111827",
        fillOpacity: 0.1,
        strokeColor: "#10b6d7",
        strokeWidth: 12,
        cornerRadius: 22,
      }),
      makeShapeLayer({
        name: "Play triangle",
        shape: "triangle",
        x: 902,
        y: 230,
        width: 210,
        height: 188,
        rotation: 90,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
      }),
      makeShapeLayer({
        name: "Wave underline",
        shape: "line",
        x: 96,
        y: 548,
        width: 560,
        height: 30,
        fill: "#ffffff",
        strokeColor: "#ff4f5f",
        strokeWidth: 14,
        lineStyle: "wave",
      }),
      makeTextLayer({
        name: "Highlight title",
        x: 76,
        y: 116,
        width: 746,
        height: 220,
        text: "INSANE\nCLUTCH",
        fontSize: 100,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Score callout",
        x: 806,
        y: 520,
        width: 336,
        height: 88,
        text: "1 HP WIN",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 7,
        align: "center",
      }),
    ],
  },
  {
    id: "podcast-guest",
    name: "Podcast Guest",
    description: "Square interview card with guest placeholder, topic title, and episode tag.",
    category: "youtube",
    previewColors: ["#ffffff", "#152033", "#10b6d7"],
    settings: { ...defaultOutputSettings, presetId: "square", width: 1080, height: 1080 },
    createLayers: () => [
      makeShapeLayer({
        name: "Warm backdrop",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#edf2f6",
        strokeWidth: 0,
      }),
      makeImageLayer({
        name: "Soft texture",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        opacity: 0.22,
        effects: { grayscale: 1, blur: 5, brightness: 118, contrast: 82, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Guest portrait frame",
        shape: "ellipse",
        x: 330,
        y: 106,
        width: 420,
        height: 420,
        fill: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 14,
      }),
      makeShapeLayer({
        name: "Episode badge",
        x: 108,
        y: 762,
        width: 864,
        height: 104,
        fill: "#152033",
        strokeWidth: 0,
        cornerRadius: 18,
      }),
      makeTextLayer({
        name: "Podcast title",
        x: 112,
        y: 568,
        width: 856,
        height: 148,
        text: "THE CREATOR\nINTERVIEW",
        fontSize: 70,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        align: "center",
        lineHeight: 0.96,
      }),
      makeTextLayer({
        name: "Episode label",
        x: 144,
        y: 786,
        width: 792,
        height: 58,
        text: "EP. 24  /  NEW GUEST",
        fontSize: 42,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 3,
        align: "center",
      }),
    ],
  },
  {
    id: "event-countdown",
    name: "Event Countdown",
    description: "Countdown announcement layout with date badge and strong event title.",
    category: "stream",
    previewColors: ["#111827", "#ffd166", "#ffffff"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Event background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.08, blur: 2, brightness: 82, contrast: 124, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Countdown card",
        x: 78,
        y: 108,
        width: 430,
        height: 430,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        rotation: -2,
      }),
      makeShapeLayer({
        name: "Date ribbon",
        x: 56,
        y: 552,
        width: 1168,
        height: 96,
        fill: "#10b6d7",
        strokeColor: "#111827",
        strokeWidth: 6,
      }),
      makeTextLayer({
        name: "Countdown number",
        x: 116,
        y: 160,
        width: 352,
        height: 196,
        text: "3",
        fontSize: 198,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ff4f5f",
        strokeColor: "#111827",
        strokeWidth: 8,
        align: "center",
      }),
      makeTextLayer({
        name: "Days label",
        x: 128,
        y: 374,
        width: 326,
        height: 78,
        text: "DAYS",
        fontSize: 56,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeWidth: 0,
        align: "center",
      }),
      makeTextLayer({
        name: "Event title",
        x: 560,
        y: 132,
        width: 600,
        height: 214,
        text: "BIG EVENT\nIS COMING",
        fontSize: 82,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 9,
        lineHeight: 0.92,
      }),
      makeTextLayer({
        name: "Date text",
        x: 104,
        y: 574,
        width: 1072,
        height: 58,
        text: "SAVE THE DATE  /  20:00 START",
        fontSize: 44,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  {
    id: "minimal-launch",
    name: "Minimal Launch",
    description: "Clean product or feature launch layout with calm whitespace and accent lines.",
    category: "cutout",
    previewColors: ["#ffffff", "#152033", "#10b6d7"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Clean background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        fill: "#f7fafc",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Product block",
        x: 730,
        y: 98,
        width: 396,
        height: 418,
        fill: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 8,
        cornerRadius: 26,
      }),
      makeShapeLayer({
        name: "Accent line one",
        shape: "line",
        x: 88,
        y: 478,
        width: 452,
        height: 18,
        strokeColor: "#10b6d7",
        strokeWidth: 12,
        lineStyle: "solid",
      }),
      makeShapeLayer({
        name: "Accent line two",
        shape: "line",
        x: 88,
        y: 520,
        width: 328,
        height: 18,
        strokeColor: "#ff4f5f",
        strokeWidth: 12,
        lineStyle: "dashed",
      }),
      makeTextLayer({
        name: "Launch eyebrow",
        x: 92,
        y: 120,
        width: 420,
        height: 54,
        text: "NEW RELEASE",
        fontSize: 38,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#10b6d7",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "Launch title",
        x: 86,
        y: 196,
        width: 568,
        height: 196,
        text: "SIMPLE\nBUT POWERFUL",
        fontSize: 78,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        lineHeight: 0.94,
      }),
      makeShapeLayer({
        name: "Tag backing",
        x: 732,
        y: 532,
        width: 392,
        height: 78,
        fill: "#152033",
        strokeWidth: 0,
        cornerRadius: 16,
      }),
      makeTextLayer({
        name: "Launch tag",
        x: 746,
        y: 542,
        width: 364,
        height: 58,
        text: "AVAILABLE NOW",
        fontSize: 36,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  {
    id: "before-after-reveal",
    name: "Before After Reveal",
    description: "Split-screen transformation layout with a strong reveal title.",
    category: "youtube",
    previewColors: ["#152033", "#ffd166", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Before texture",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 640,
        height: 720,
        effects: { grayscale: 1, blur: 2, brightness: 72, contrast: 116, mosaic: 0 },
      }),
      makeImageLayer({
        name: "After texture",
        imageKey: "sample-bg",
        x: 640,
        y: 0,
        width: 640,
        height: 720,
        effects: { grayscale: 0, blur: 0, brightness: 112, contrast: 126, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Reveal divider",
        x: 612,
        y: -28,
        width: 56,
        height: 776,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
        rotation: 3,
      }),
      makeTextLayer({
        name: "Before label",
        x: 70,
        y: 560,
        width: 440,
        height: 76,
        text: "BEFORE",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 6,
      }),
      makeTextLayer({
        name: "After label",
        x: 768,
        y: 560,
        width: 420,
        height: 76,
        text: "AFTER",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 6,
        align: "right",
      }),
      makeTextLayer({
        name: "Reveal title",
        x: 144,
        y: 94,
        width: 992,
        height: 134,
        text: "TOTAL TRANSFORMATION",
        fontSize: 78,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ff4f5f",
        strokeColor: "#ffffff",
        strokeWidth: 8,
        align: "center",
      }),
    ],
  },
  {
    id: "music-premiere",
    name: "Music Premiere",
    description: "Stream-style premiere layout with title lockup and live badge.",
    category: "stream",
    previewColors: ["#111827", "#7c3aed", "#ffd166"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Premiere background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.2, blur: 3, brightness: 62, contrast: 138, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Stage glow plate",
        x: 78,
        y: 90,
        width: 1124,
        height: 478,
        fill: "#111827",
        fillOpacity: 0.72,
        strokeColor: "#7c3aed",
        strokeWidth: 12,
        cornerRadius: 28,
      }),
      makeShapeLayer({
        name: "Live pill",
        x: 854,
        y: 86,
        width: 250,
        height: 76,
        fill: "#ff4f5f",
        strokeColor: "#ffffff",
        strokeWidth: 5,
        cornerRadius: 18,
      }),
      makeTextLayer({
        name: "Premiere label",
        x: 886,
        y: 104,
        width: 186,
        height: 44,
        text: "LIVE",
        fontSize: 38,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 3,
        align: "center",
      }),
      makeTextLayer({
        name: "Premiere title",
        x: 132,
        y: 208,
        width: 940,
        height: 194,
        text: "NEW TRACK\nPREMIERE",
        fontSize: 94,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#7c3aed",
        strokeWidth: 8,
        lineHeight: 0.88,
      }),
      makeShapeLayer({
        name: "Audio wave",
        shape: "line",
        x: 144,
        y: 492,
        width: 690,
        height: 34,
        strokeColor: "#ffd166",
        strokeWidth: 16,
        lineStyle: "wave",
      }),
    ],
  },
  {
    id: "vertical-tip",
    name: "Vertical Tip",
    description: "Fast portrait tip card for short-form tutorial clips.",
    category: "shorts",
    previewColors: ["#152033", "#10b6d7", "#ffffff"],
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Tip background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0.25, blur: 6, brightness: 74, contrast: 118, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Tip card",
        x: 92,
        y: 440,
        width: 896,
        height: 760,
        fill: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 12,
        cornerRadius: 34,
      }),
      makeTextLayer({
        name: "Tip number",
        x: 146,
        y: 510,
        width: 220,
        height: 170,
        text: "#1",
        fontSize: 128,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#10b6d7",
        strokeColor: "#152033",
        strokeWidth: 6,
      }),
      makeTextLayer({
        name: "Tip title",
        x: 154,
        y: 742,
        width: 770,
        height: 300,
        text: "SAVE\nTHIS TIP",
        fontSize: 126,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffd166",
        strokeWidth: 6,
        lineHeight: 0.92,
        align: "center",
      }),
      makeShapeLayer({
        name: "Bottom bar",
        x: 132,
        y: 1364,
        width: 816,
        height: 76,
        fill: "#ff4f5f",
        strokeWidth: 0,
        cornerRadius: 18,
      }),
    ],
  },
  {
    id: "reaction-clip",
    name: "Reaction Clip",
    description: "Portrait reaction layout with punchy quote and emoji-like badge.",
    category: "shorts",
    previewColors: ["#111827", "#ff4f5f", "#ffd166"],
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Reaction backdrop",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0, blur: 4, brightness: 68, contrast: 142, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Reaction bubble",
        shape: "ellipse",
        x: 188,
        y: 246,
        width: 704,
        height: 520,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 14,
        rotation: -4,
      }),
      makeTextLayer({
        name: "Reaction mark",
        x: 302,
        y: 350,
        width: 470,
        height: 280,
        text: "NO\nWAY!",
        fontSize: 128,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 8,
        align: "center",
        lineHeight: 0.86,
      }),
      makeShapeLayer({
        name: "Quote panel",
        x: 106,
        y: 1088,
        width: 868,
        height: 318,
        fill: "#ff4f5f",
        strokeColor: "#ffffff",
        strokeWidth: 10,
        cornerRadius: 30,
      }),
      makeTextLayer({
        name: "Reaction caption",
        x: 158,
        y: 1168,
        width: 764,
        height: 162,
        text: "WATCH\nTHE END",
        fontSize: 84,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 7,
        align: "center",
        lineHeight: 0.9,
      }),
    ],
  },
  {
    id: "daily-vlog",
    name: "Daily Vlog",
    description: "Vertical lifestyle start with a clean date block and story title.",
    category: "shorts",
    previewColors: ["#f7fafc", "#152033", "#10b6d7"],
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Vlog photo",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0.05, blur: 2, brightness: 92, contrast: 104, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Soft caption panel",
        x: 84,
        y: 1168,
        width: 912,
        height: 392,
        fill: "#ffffff",
        fillOpacity: 0.94,
        strokeColor: "#152033",
        strokeWidth: 8,
        cornerRadius: 28,
      }),
      makeTextLayer({
        name: "Vlog title",
        x: 142,
        y: 1244,
        width: 796,
        height: 188,
        text: "DAY IN\nMY LIFE",
        fontSize: 86,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#10b6d7",
        strokeWidth: 4,
        align: "center",
        lineHeight: 0.94,
      }),
      makeTextLayer({
        name: "Vlog date",
        x: 222,
        y: 1494,
        width: 636,
        height: 70,
        text: "TODAY'S HIGHLIGHTS",
        fontSize: 42,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ff4f5f",
        strokeWidth: 0,
        align: "center",
      }),
      makeShapeLayer({
        name: "Top accent",
        x: 116,
        y: 206,
        width: 848,
        height: 36,
        fill: "#10b6d7",
        strokeWidth: 0,
        rotation: -2,
      }),
    ],
  },
  {
    id: "fitness-challenge",
    name: "Fitness Challenge",
    description: "Portrait challenge thumbnail with timer badge and progress energy.",
    category: "shorts",
    previewColors: ["#111827", "#10b6d7", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Fitness backdrop",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0.2, blur: 3, brightness: 70, contrast: 132, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Timer badge",
        shape: "ellipse",
        x: 650,
        y: 190,
        width: 300,
        height: 300,
        fill: "#ff4f5f",
        strokeColor: "#ffffff",
        strokeWidth: 12,
      }),
      makeTextLayer({
        name: "Timer text",
        x: 692,
        y: 278,
        width: 216,
        height: 116,
        text: "30s",
        fontSize: 76,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 6,
        align: "center",
      }),
      makeTextLayer({
        name: "Challenge title",
        x: 104,
        y: 720,
        width: 872,
        height: 342,
        text: "CAN YOU\nFINISH?",
        fontSize: 116,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        align: "center",
        lineHeight: 0.9,
      }),
      makeShapeLayer({
        name: "Progress line",
        shape: "line",
        x: 154,
        y: 1260,
        width: 772,
        height: 28,
        strokeColor: "#10b6d7",
        strokeWidth: 18,
        lineStyle: "dashed",
      }),
    ],
  },
  {
    id: "profile-cutout",
    name: "Profile Cutout",
    description: "Clean creator cutout frame with nameplate and profile-safe space.",
    category: "cutout",
    previewColors: ["#ffffff", "#10b6d7", "#152033"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Profile background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        fill: "#ffffff",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Creator cutout zone",
        shape: "ellipse",
        x: 728,
        y: 82,
        width: 360,
        height: 480,
        fill: "#edf2f6",
        strokeColor: "#10b6d7",
        strokeWidth: 14,
      }),
      makeShapeLayer({
        name: "Nameplate",
        x: 88,
        y: 488,
        width: 610,
        height: 96,
        fill: "#152033",
        strokeWidth: 0,
        cornerRadius: 18,
      }),
      makeTextLayer({
        name: "Profile title",
        x: 82,
        y: 144,
        width: 608,
        height: 180,
        text: "MEET THE\nCREATOR",
        fontSize: 82,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#10b6d7",
        strokeWidth: 4,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Profile name",
        x: 122,
        y: 512,
        width: 542,
        height: 56,
        text: "CHANNEL NAME",
        fontSize: 40,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeWidth: 0,
        align: "center",
      }),
    ],
  },
  {
    id: "product-cutout",
    name: "Product Cutout",
    description: "Product hero cutout layout with price badge and feature callout.",
    category: "cutout",
    previewColors: ["#f7fafc", "#ff4f5f", "#ffd166"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Product background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        fill: "#f7fafc",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Product cutout box",
        x: 700,
        y: 100,
        width: 390,
        height: 430,
        fill: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 10,
        cornerRadius: 30,
        rotation: 2,
      }),
      makeShapeLayer({
        name: "Price burst",
        shape: "ellipse",
        x: 916,
        y: 446,
        width: 210,
        height: 138,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
        rotation: -8,
      }),
      makeTextLayer({
        name: "Product headline",
        x: 92,
        y: 142,
        width: 568,
        height: 210,
        text: "NEW\nGEAR",
        fontSize: 104,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ff4f5f",
        strokeColor: "#152033",
        strokeWidth: 8,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Product caption",
        x: 100,
        y: 430,
        width: 520,
        height: 76,
        text: "FIRST LOOK",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffffff",
        strokeWidth: 4,
      }),
      makeTextLayer({
        name: "Price text",
        x: 948,
        y: 488,
        width: 150,
        height: 58,
        text: "HOT",
        fontSize: 44,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeWidth: 0,
        align: "center",
      }),
    ],
  },
  {
    id: "food-cutout",
    name: "Food Cutout",
    description: "Food thumbnail frame with plate cutout area and recipe title.",
    category: "cutout",
    previewColors: ["#ffffff", "#ffd166", "#ff4f5f"],
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeShapeLayer({
        name: "Food background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        fill: "#ffffff",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Plate cutout zone",
        shape: "ellipse",
        x: 690,
        y: 110,
        width: 414,
        height: 414,
        fill: "#fff4c7",
        strokeColor: "#ff4f5f",
        strokeWidth: 12,
      }),
      makeShapeLayer({
        name: "Recipe ribbon",
        x: 82,
        y: 492,
        width: 590,
        height: 92,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 6,
        cornerRadius: 20,
      }),
      makeTextLayer({
        name: "Food title",
        x: 86,
        y: 132,
        width: 570,
        height: 206,
        text: "5 MIN\nRECIPE",
        fontSize: 96,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ff4f5f",
        strokeColor: "#111827",
        strokeWidth: 7,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Recipe caption",
        x: 116,
        y: 516,
        width: 530,
        height: 54,
        text: "EASY DINNER",
        fontSize: 40,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeWidth: 0,
        align: "center",
      }),
    ],
  },
  {
    id: "fashion-cutout",
    name: "Fashion Cutout",
    description: "Style lookbook cutout layout with editorial headline and outfit slot.",
    category: "cutout",
    previewColors: ["#edf2f6", "#152033", "#10b6d7"],
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeShapeLayer({
        name: "Lookbook background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        fill: "#edf2f6",
        strokeWidth: 0,
      }),
      makeShapeLayer({
        name: "Outfit cutout zone",
        x: 214,
        y: 304,
        width: 652,
        height: 840,
        fill: "#ffffff",
        strokeColor: "#152033",
        strokeWidth: 12,
        cornerRadius: 36,
      }),
      makeShapeLayer({
        name: "Editorial accent",
        x: 100,
        y: 1216,
        width: 880,
        height: 46,
        fill: "#10b6d7",
        strokeWidth: 0,
        rotation: -2,
      }),
      makeTextLayer({
        name: "Lookbook title",
        x: 120,
        y: 1304,
        width: 840,
        height: 220,
        text: "STYLE\nCHECK",
        fontSize: 108,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#152033",
        strokeColor: "#ffffff",
        strokeWidth: 8,
        align: "center",
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Lookbook tag",
        x: 176,
        y: 1588,
        width: 728,
        height: 64,
        text: "TODAY'S OUTFIT",
        fontSize: 44,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#10b6d7",
        strokeColor: "#152033",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  ...motionTemplates,
  ...scheduleTemplates,
];
