import { defaultOutputSettings } from "./presets";
import { makeImageLayer, makeShapeLayer, makeTextLayer } from "./layerFactory";
import { createInitialLayers } from "./sampleData";
import type { OutputSettings, ThumbnailLayer } from "./types";

export interface DefaultTemplateDefinition {
  id: string;
  name: string;
  description: string;
  settings: OutputSettings;
  createLayers: () => ThumbnailLayer[];
}

export const defaultTemplates: DefaultTemplateDefinition[] = [
  {
    id: "creator-live",
    name: "Creator Live",
    description: "Bold livestream thumbnail with title plate and platform tag.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: createInitialLayers,
  },
  {
    id: "product-review",
    name: "Product Review",
    description: "Review layout with large product area, score badge, and verdict text.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Soft background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0, blur: 4, brightness: 78, contrast: 120, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Product frame",
        shape: "rect",
        x: 716,
        y: 92,
        width: 430,
        height: 430,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        rotation: 3,
      }),
      makeShapeLayer({
        name: "Score badge",
        shape: "ellipse",
        x: 884,
        y: 486,
        width: 220,
        height: 132,
        fill: "#ffd166",
        strokeColor: "#111827",
        strokeWidth: 8,
        rotation: -8,
      }),
      makeTextLayer({
        name: "Review title",
        x: 70,
        y: 86,
        width: 600,
        height: 220,
        text: "WORTH\nBUYING?",
        fontSize: 96,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        lineHeight: 0.9,
      }),
      makeTextLayer({
        name: "Verdict",
        x: 96,
        y: 526,
        width: 560,
        height: 74,
        text: "FULL REVIEW",
        fontSize: 48,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 5,
      }),
      makeTextLayer({
        name: "Score text",
        x: 902,
        y: 518,
        width: 180,
        height: 72,
        text: "9/10",
        fontSize: 54,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffffff",
        strokeWidth: 4,
        align: "center",
      }),
    ],
  },
  {
    id: "tutorial-steps",
    name: "Tutorial Steps",
    description: "Structured how-to thumbnail with numbered chips and a clear action title.",
    settings: { ...defaultOutputSettings, presetId: "youtube-720" },
    createLayers: () => [
      makeImageLayer({
        name: "Desk background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        effects: { grayscale: 0.16, blur: 2, brightness: 86, contrast: 118, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Header band",
        x: 0,
        y: 0,
        width: 1280,
        height: 150,
        fill: "#152033",
        strokeWidth: 0,
      }),
      makeTextLayer({
        name: "How-to title",
        x: 76,
        y: 46,
        width: 820,
        height: 92,
        text: "MAKE IT IN 5 MINUTES",
        fontSize: 58,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#10b6d7",
        strokeWidth: 5,
      }),
      ...[0, 1, 2].map((index) =>
        makeShapeLayer({
          name: `Step ${index + 1} chip`,
          shape: "rect",
          x: 90 + index * 382,
          y: 468,
          width: 292,
          height: 118,
          fill: index === 1 ? "#ff4f5f" : "#ffffff",
          strokeColor: "#111827",
          strokeWidth: 7,
          rotation: index === 1 ? -2 : 2,
        }),
      ),
      ...["Plan", "Build", "Export"].map((text, index) =>
        makeTextLayer({
          name: `Step ${index + 1} label`,
          x: 112 + index * 382,
          y: 494,
          width: 248,
          height: 68,
          text: `${index + 1}. ${text}`,
          fontSize: 42,
          fontFamily: "Arial Black, Arial, sans-serif",
          fontWeight: "900",
          color: index === 1 ? "#ffffff" : "#111827",
          strokeColor: index === 1 ? "#111827" : "#ffffff",
          strokeWidth: 3,
          align: "center",
        }),
      ),
    ],
  },
  {
    id: "shorts-quote",
    name: "Shorts Quote",
    description: "Vertical quote-first layout for Shorts, Reels, and portrait clips.",
    settings: { ...defaultOutputSettings, presetId: "portrait", width: 1080, height: 1920 },
    createLayers: () => [
      makeImageLayer({
        name: "Portrait background",
        imageKey: "sample-bg",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        effects: { grayscale: 0, blur: 6, brightness: 70, contrast: 128, mosaic: 0 },
      }),
      makeShapeLayer({
        name: "Quote panel",
        x: 86,
        y: 520,
        width: 908,
        height: 610,
        fill: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 10,
        opacity: 0.94,
      }),
      makeTextLayer({
        name: "Quote text",
        x: 134,
        y: 612,
        width: 812,
        height: 386,
        text: "ONE IDEA\nCHANGED\nEVERYTHING",
        fontSize: 112,
        fontFamily: "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif",
        fontWeight: "900",
        color: "#111827",
        strokeColor: "#ffd166",
        strokeWidth: 6,
        align: "center",
        lineHeight: 0.94,
      }),
      makeShapeLayer({
        name: "Accent slash",
        x: 92,
        y: 1238,
        width: 896,
        height: 42,
        fill: "#ff4f5f",
        strokeWidth: 0,
        rotation: -3,
      }),
      makeTextLayer({
        name: "Series tag",
        x: 130,
        y: 1304,
        width: 820,
        height: 88,
        text: "SHORT CLIP",
        fontSize: 58,
        fontFamily: "Arial Black, Arial, sans-serif",
        fontWeight: "900",
        color: "#ffffff",
        strokeColor: "#111827",
        strokeWidth: 7,
        align: "center",
      }),
    ],
  },
];
